apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: web-server
spec:
  replicas: 2
  selector:
    matchLabels:
      application: web-server
  template:
    metadata:
      labels:
        application: web-server
    spec:
      containers:
      - name: web-server
        image: nginx:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80