apiVersion: v1
kind: Service
metadata:
  name: web-server
  labels:
    application: web-server
spec:
  selector:
    application: web-server
  type: LoadBalancer
  ports:
    - port: 80
      name: http
      targetPort: 80
status:
  loadBalancer:
    ingress:
      - ip: 192.168.99.101
